server:
  port: 8888
   
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
  
       
spring:  
  cloud:
     config:
       server:
         git:
           uri: '{cipher}AQBgip7ZFkXZOBvSuTU1ONDrrA9cqrkrQJZ+iMQSDisACzDnMQpGQCAfNcBF7C+9Ixb7d3Cy1eGCxl6mvl/mTZlmvos+N6ahfiOiATruQSHYdo6Lixj+srIW6ICNTqJDVbXi95tgvcbA1n2enDbQUX3HaZtcBZsAPnlk3WVNKpKIF8cEUpJ4kqzdTX+UBa9wmELsuPQe/xsGwL0am8ZcvQGcAhVOMbMMcmQ+QAOW1a7oGl1nAFXOmKngpoiy96xQ7sn6FFptw9Ykw0qY2d789++L9AXj9x2KubXVijH1u2cflrD2B3kIPv0zbB4fuqR5bP9nqScZKb7925I2h9TgIWp7vVp/7M22zn4bUuzehaepatjFJmOyEAtYYFXAGU+pDsXiiAknvbGMjyAqohWLKTt3waZAgrfPKU0jzOwFkf7DHw=='
           basedir: target/config 
      

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
       defaultZone: http://15900455491:skdjf7782c@${domain.name:localhost}:8761/eureka/
    
       
security:
  user:
    name: 15900455491
    password: skdjf7782c
  ignored:
    - /encrypt*



         
   



    

